export const INIT_APP = 'INIT_APP';

export const GET_RANDOM_USERS_REQUEST = 'GET_RANDOM_USERS_REQUEST';
export const GET_RANDOM_USERS_SUCCESS = 'GET_RANDOM_USERS_SUCCESS';
export const GET_RANDOM_USERS_FAIL = 'GET_RANDOM_USERS_FAIL';
